### PR TITLE
resolved type check using isinstance. If wrong type exit from the script

### PR DESCRIPTION
**Pull request by Cereal84**
Maybe I've resolved your POGs.
#1
# hacktoberfest

### CODE REVIEW

**Comment by luanjpb** [comment]
Thnaks ! :)

**Comment by Cereal84** [comment]
Can you write down the conflict ?

**Comment by Cereal84** [comment]
Ok, I've seen now the pull request about "
Hi I made some minor changes to make your code PEP8 compiliant
"
Try to fix the merge conflict

**Comment by Cereal84** [comment]
Done :)

**Pull request merged**
